services:
  db:
    image: postgres:16
    container_name: sustainability-impact-azure-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: impact_user
      POSTGRES_PASSWORD: impact_password
      POSTGRES_DB: impact_logger

    ports:
      - "5433:5432"

    volumes:
      - azure_postgres_data:/var/lib/postgresql/data

volumes:
  azure_postgres_data: